export const temple = {
  nameMl: "മണ്ടത്ര ശ്രീ മുത്തപ്പൻ ഭഗവതി ക്ഷേത്ര കമ്മിറ്റി",
  shortNameMl: "മണ്ടത്ര ശ്രീ മുത്തപ്പൻ ക്ഷേത്രം",
  nameEn: "Mandathra Sree Muthappan Bhagavathi Temple Committee",
  shortNameEn: "Mandathra Kshethram",
  regNo: "603/99",
  addressMl: "പി.ഒ. കൂളിമുട്ടം, 680691",
  addressEn: "P.O. Koolimuttam, Thrissur, Kerala - 680691",
  phonePresident: "+91 90480 55144",
  phoneSecretary: "+91 94952 24141",
  email: "info@mandathratemple.org",
  mapsUrl: "https://share.google/ykFbz9xgrCEjdyXmx",
  whatsappUrl: "https://wa.me/919495224141",
};

export const media = {
  logo: "/logowebsite.webp",
  logoOriginal: "/logowebsite.jpeg",
  hero: "/temple-exterior.webp",
  templeWide: "/temple-event-07-56-06.webp",
  templeWideAlt: "/temple-event-07-56-41.webp",
  templeCourtyard: "/temple-event-07-57-02.webp",
  entranceLamp: "/temple-event-07-58-00.webp",
  entranceVertical: "/temple-event-07-58-20.webp",
  innerSanctum: "/inner-sanctum-kalam.webp",
  kalvilakku: "/kalvilakku-courtyard.webp",
  stoneLion: "/stone-lion.webp",
  exteriorPortrait: "/temple-exterior-portrait.webp",
  courtyardThumb: "/temple-courtyard-landscape.webp",
};

export const galleryItems = [
  {
    src: media.hero,
    alt: "Mandathra Sree Muthappan Bhagavathi Temple main shrine with Kerala tiled roof",
    category: "Temple",
    span: "wide",
  },
  {
    src: media.entranceLamp,
    alt: "Temple entrance with traditional brass lamp and lion sculptures",
    category: "Temple Events",
    span: "tall",
  },
  {
    src: media.templeWide,
    alt: "Wide view of the Mandathra temple campus surrounded by coconut trees",
    category: "Temple",
  },
  {
    src: media.innerSanctum,
    alt: "Inner sanctum ritual decoration for devotional worship",
    category: "Festivals",
    span: "tall",
    contain: true,
  },
  {
    src: media.kalvilakku,
    alt: "Traditional Kerala kalvilakku lamp in the temple courtyard",
    category: "Rituals",
    contain: true,
  },
  {
    src: media.stoneLion,
    alt: "Gold-toned stone lion sculpture at the temple",
    category: "Temple",
    contain: true,
  },
  {
    src: media.entranceVertical,
    alt: "Vertical view of the temple entrance canopy and shrine path",
    category: "Temple Events",
    span: "tall",
  },
  {
    src: media.templeCourtyard,
    alt: "Temple courtyard and pathway during a quiet devotional day",
    category: "Temple",
  },
];

export const committeeMembers = [
  {
    roleMl: "പ്രസിഡന്റ്",
    roleEn: "President",
    nameMl: "എം.വി. സതീഷ്കുമാർ",
    nameEn: "M.V. Satheeshkumar",
    phone: "9048055144",
    place: "Kodungallur",
    officer: true,
  },
  {
    roleMl: "സെക്രട്ടറി",
    roleEn: "Secretary",
    nameMl: "എം.ആർ. സന്തോഷ്",
    nameEn: "M.R. Santhosh",
    phone: "9495224141",
    place: "Koolimuttam",
    officer: true,
  },
  {
    roleMl: "ട്രഷറർ",
    roleEn: "Treasurer",
    nameMl: "എം.എസ്. പ്രഭാകരൻ",
    nameEn: "M.S. Prabhakaran",
    phone: "7907338712",
    place: "Koolimuttam",
    officer: true,
  },
  {
    roleMl: "വൈസ് പ്രസിഡന്റ്",
    roleEn: "Vice President",
    nameMl: "അജിത പ്രഭാകരൻ",
    nameEn: "Ajitha Prabhakaran",
    phone: "9747611856",
    place: "Koolimuttam",
    officer: true,
  },
  {
    roleMl: "ജോയിന്റ് സെക്രട്ടറി",
    roleEn: "Joint Secretary",
    nameMl: "ശാലിനി ഉണ്ണികൃഷ്ണൻ",
    nameEn: "Shalini Unnikrishnan",
    phone: "9497559878",
    place: "Kara",
    officer: true,
  },
  {
    roleMl: "ഭരണസമിതി അംഗം",
    roleEn: "Executive Member",
    nameMl: "എം.എസ്. കൃഷ്ണൻ",
    nameEn: "M.S. Krishnan",
    phone: "9562198013",
    place: "S.N. Puram",
  },
  {
    roleMl: "ഭരണസമിതി അംഗം",
    roleEn: "Executive Member",
    nameMl: "അനിത ഷൺമുഖൻ",
    nameEn: "Anitha Shanmughan",
    phone: "6282358380",
    place: "Koolimuttam",
  },
  {
    roleMl: "ഭരണസമിതി അംഗം",
    roleEn: "Executive Member",
    nameMl: "ബീന ഹരിലാൽ",
    nameEn: "Beena Harilal",
    phone: "8590064710",
    place: "P. Vempallur",
  },
  {
    roleMl: "ഭരണസമിതി അംഗം",
    roleEn: "Executive Member",
    nameMl: "എം.വി. ഉണ്ണികൃഷ്ണൻ",
    nameEn: "M.V. Unnikrishnan",
    phone: "9447673806",
    place: "Kara",
  },
  {
    roleMl: "ഭരണസമിതി അംഗം",
    roleEn: "Executive Member",
    nameMl: "എം.യു. ബാബു",
    nameEn: "M.U. Babu",
    phone: "9895511002",
    place: "Kara",
  },
  {
    roleMl: "ഭരണസമിതി അംഗം",
    roleEn: "Executive Member",
    nameMl: "എം.ആർ. ശിവദാസൻ",
    nameEn: "M.R. Sivadasan",
    phone: "9980293350",
    place: "Edavilangu",
  },
];
